/* CHEFS */
use tp_resto
INSERT INTO CHEFS (NOMBRE) VALUES ('GUTIERREZ PABLO')
INSERT INTO CHEFS (NOMBRE) VALUES ('BERNARDEZ JIMENA')

/* DIA_CHEF */
INSERT INTO DIAsxCHEF (IDCHEF, horarioENTRADA, horarioSALIDA) VALUES (1,'2012/05/17 06:00:00', '2012/05/17 12:15:00')
INSERT INTO DIAsxCHEF (IDCHEF, horarioENTRADA, horarioSALIDA) VALUES (2,'2012/05/17 12:15:00', '2012/05/17 18:15:00')

/* PROVEEDORES */
INSERT INTO PROVEEDORES (nombre, eMAIL, TELefono) VALUES ('CARN Y VERD KLOSTER','CYVKLOSTER@HOTMAIL.COM', '123456')
INSERT INTO PROVEEDORES (nombre, eMAIL, TELefono) VALUES ('GRANJA VIER','GRANJAVIER@JAVIER.COM.AR', '56789')
INSERT INTO PROVEEDORES (nombre, eMAIL, TELefono) VALUES ('COTO','INFO@COTO.COM.AR', '0800')


/* RUBROS */
INSERT INTO RUBROS (rubro) VALUES ('CARNICERIA')
INSERT INTO RUBROS (rubro)VALUES ('PRODUCTOS DE GRANJA')
INSERT INTO RUBROS (rubro)VALUES ('VERDULERIA')
INSERT INTO RUBROS (rubro)VALUES ('LACTEOS')
INSERT INTO RUBROS (rubro)VALUES ('FRUTAS')
INSERT INTO RUBROS (rubro) VALUES ('ALMACEN')

/* RUBROS X PROVEEDOR */
INSERT INTO RUBROSxprov (IDRUBRO, IDPROV) VALUES (1 , 5)
INSERT INTO RUBROSxprov (IDRUBRO, IDPROV) VALUES (2 , 6)
INSERT INTO RUBROSxprov(IDRUBRO, IDPROV) VALUES (3 , 5)
INSERT INTO RUBROSxprov(IDRUBRO, IDPROV) VALUES (1 , 6)
INSERT INTO RUBROSxprov(IDRUBRO, IDPROV) VALUES (2 , 8)
INSERT INTO RUBROSxprov(IDRUBRO, IDPROV) VALUES (3 , 8)
INSERT INTO RUBROSxprov(IDRUBRO, IDPROV) VALUES (4 , 5)
INSERT INTO RUBROSxprov(IDRUBRO, IDPROV) VALUES (5 , 6)
INSERT INTO RUBROSxprov(IDRUBRO, IDPROV) VALUES (6 , 8)



/* INGREDIENTES_X_PROVEEDOR */
INSERT INTO INGR_X_PROV (IDINGREDIENTE, IDPROV,espera) VALUES (1 , 5,1)
INSERT INTO INGR_X_PROV (IDINGREDIENTE, IDPROV,espera) VALUES (1 , 6,2)
INSERT INTO INGR_X_PROV(IDINGREDIENTE, IDPROV,espera) VALUES (2 , 8,3)
INSERT INTO INGR_X_PROV(IDINGREDIENTE, IDPROV,espera) VALUES (3 , 5,1)
INSERT INTO INGR_X_PROV(IDINGREDIENTE, IDPROV,espera) VALUES (3 , 6,2)
INSERT INTO INGR_X_PROV(IDINGREDIENTE, IDPROV,espera) VALUES (4 , 8,3)
INSERT INTO INGR_X_PROV(IDINGREDIENTE, IDPROV,espera) VALUES (4 , 5,1)
INSERT INTO INGR_X_PROV(IDINGREDIENTE, IDPROV,espera) VALUES (5 , 6,2)
INSERT INTO INGR_X_PROV(IDINGREDIENTE, IDPROV,espera) VALUES (6 , 8,3)
INSERT INTO INGR_X_PROV(IDINGREDIENTE, IDPROV,espera) VALUES (7 , 5,1)

SET DATEFORMAT DMY;
