USE TP_resto;

/* INGREDIENTES */
INSERT INTO INGREDIENTES(INGREDIENTE) VALUES ('PECETO');
INSERT INTO INGREDIENTES(INGREDIENTE) VALUES ('PAN RALLADO');
INSERT INTO INGREDIENTES(INGREDIENTE) VALUES ('HUEVO');
INSERT INTO INGREDIENTES(INGREDIENTE) VALUES ('PEREJIL');
INSERT INTO INGREDIENTES(INGREDIENTE) VALUES ('AJO');
INSERT INTO INGREDIENTES(INGREDIENTE) VALUES ('LECHE');
INSERT INTO INGREDIENTES(INGREDIENTE) VALUES ('HARINA');
INSERT INTO INGREDIENTES(INGREDIENTE) VALUES ('DULCE DE LECHE');


/* UNIDADES */
INSERT INTO UNIDADES(UNIDAD) VALUES ('GRAMOS');
INSERT INTO UNIDADES(UNIDAD) VALUES ('CENTIMETROS CUBICOS');
INSERT INTO UNIDADES(UNIDAD) VALUES ('UNIDADES');
INSERT INTO UNIDADES(UNIDAD) VALUES ('CUCHARADITAS');
INSERT INTO UNIDADES(UNIDAD) VALUES ('PIZCA');
INSERT INTO UNIDADES(UNIDAD) VALUES ('CUCHARADA');
INSERT INTO UNIDADES(UNIDAD) VALUES ('TAZA');
INSERT INTO UNIDADES(UNIDAD) VALUES ('CANTIDAD NECESARIA');

/* CATEGORIAS */
INSERT INTO CATEGORIAS(CATEGORIA) VALUES ('PLATO FUERTE');
INSERT INTO CATEGORIAS(CATEGORIA) VALUES ('POSTRE');

/* PLATOS */
INSERT INTO recetas (receta, TIEMPO, DIFICULTAD, precio, IDCATEGORIA) 
VALUES('MILANESAS', 30, 5, 40, 1);
INSERT INTO recetas (receta, TIEMPO, DIFICULTAD, precio, IDCATEGORIA) 
VALUES('PANQUEQUES CON DULCE DE LECHE', 25, 5, 28, 2);

/* INGREDIENTES_X_PLATO */
INSERT INTO INGR_X_receta(IDINGREDIENTE, IDreceta, IDUNIDAD, CANTIDAD)
VALUES(1, 1, 1, 100);
INSERT INTO INGR_X_receta(IDINGREDIENTE, IDreceta, IDUNIDAD, CANTIDAD)
VALUES(2, 1, 1, 100);
INSERT INTO INGR_X_receta(IDINGREDIENTE, IDreceta, IDUNIDAD, CANTIDAD)
VALUES(3, 1, 3, 2);
INSERT INTO INGR_X_receta(IDINGREDIENTE, IDreceta, IDUNIDAD, CANTIDAD)
VALUES(4, 1, 4, 2);
INSERT INTO INGR_X_receta(IDINGREDIENTE, IDreceta, IDUNIDAD, CANTIDAD)
VALUES(5, 1, 4, 1);

INSERT INTO INGR_X_receta(IDINGREDIENTE, IDreceta, IDUNIDAD, CANTIDAD)
VALUES(6, 2, 2, 500);
INSERT INTO INGR_X_receta(IDINGREDIENTE, IDreceta, IDUNIDAD, CANTIDAD)
VALUES(7, 2, 7, 1);
INSERT INTO INGR_X_receta(IDINGREDIENTE, IDreceta, IDUNIDAD, CANTIDAD)
VALUES(3, 2, 3, 3);
INSERT INTO INGR_X_receta(IDINGREDIENTE, IDreceta, IDUNIDAD, CANTIDAD)
VALUES(8, 2, 8, 1);

/* MOZOS */
INSERT INTO MOZXS (NOMBRE, COMISION) VALUES ('SIMON ANGEL', 1.4);
INSERT INTO MOZXS (NOMBRE, COMISION) VALUES ('KLOSTER DANIEL', 1.3);

/* PEDIDOS */
SET DATEFORMAT 'YMD'
GO
INSERT INTO PEDIDOS (MESA, FORMAPAGO, IDMOZO) 
VALUES (1, 'E', 1);

INSERT INTO PLATOSXPEDIDO(IDPEDIDO, IDRECETA, fyhpedido, fyhentrega)
VALUES (1, 1, '2012/05/17 12:00', '2012/05/17 12:09')

INSERT INTO PLATOSXPEDIDO(IDPEDIDO, IDRECETA, fyhpedido, fyhentrega)
VALUES (1, 1, '2012/05/17 12:05', '2012/05/17 12:11')

--
INSERT INTO PEDIDOS (MESA, FORMAPAGO, IDMOZO) 
VALUES (2, 'T', 2);

INSERT INTO PLATOSXPEDIDO(IDPEDIDO, IDRECETA, fyhpedido, fyhentrega)
VALUES (2, 2, '2012/05/17 12:00', '2012/05/17 12:30')

INSERT INTO PLATOSXPEDIDO(IDPEDIDO, IDRECETA, fyhpedido, fyhentrega)
VALUES (2, 2, '2012/05/17 12:00', '2012/05/17 12:30')
--
INSERT INTO PEDIDOS (MESA, FORMAPAGO, IDMOZO) 
VALUES (1, 'E', 1);

INSERT INTO PLATOSXPEDIDO(IDPEDIDO, IDRECETA, fyhpedido, fyhentrega)
VALUES (3, 1, '2012/05/17 12:30', '2012/05/17 13:00')

INSERT INTO PLATOSXPEDIDO(IDPEDIDO, IDRECETA, fyhpedido, fyhentrega)
VALUES (3, 1, '2012/05/17 12:30', '2012/05/17 13:00')

INSERT INTO PLATOSXPEDIDO(IDPEDIDO, IDRECETA, fyhpedido, fyhentrega)
VALUES (3, 2, '2012/05/17 13:20', '2012/05/17 13:45')

INSERT INTO PLATOSXPEDIDO(IDPEDIDO, IDRECETA, fyhpedido, fyhentrega)
VALUES (3, 2, '2012/05/17 13:20', '2012/05/17 13:45')

insert into pedidos(mesa,idmozo,formapago) values ('1','1','e')
insert into platosxpedido(idpedido,idreceta,fyhpedido,fyhentrega) values ('4','3','2012/05/17 12:11','2012/05/17 13:11')

insert into pedidos(mesa,idmozo,formapago) values ('1','1','e')
insert into platosxpedido(idpedido,idreceta,fyhpedido,fyhentrega) values ('5','4','2012/05/17 12:11','2012/05/17 13:11')

select * from pedidos

--

